#!/bin/bash

export PATH="${PATH}:${HOME}/.local/bin/"

swww-daemon
DIR=$HOME/.wallpaper
PICS=($(ls ${DIR}))

RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}

echo RANDOMPICS
swww img ${DIR}/${RANDOMPICS} --transition-type grow --transition-fps 60 --transition-duration 1.0 --transition-pos 0.810,0.972 --transition-bezier 0.65,0,0.35,1 --transition-step 255
wal -i ${DIR}/${RANDOMPICS}

echo "Successfully set a new wallpaper and generated colors from it."

sed -i 's,''path = .*,''path = '"${DIR}/${RANDOMPICS}"',1' ${HOME}/.config/hypr/hyprlock.conf
pywalfox update
pywal-discord -t default
${HOME}/.config/dunst/initdust.sh
